<?php
###############################################################################################################################
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOxdllclldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxdlc:;;;;;;;;:lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc:;;;;;;;;;;:::;:ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc::;;;;;;::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;:::::::::::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;::;::::::::::::::::::::::::ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::::::::::::::::::::::::::::::::::::l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMWNX0kxocc:::::::::::::::::::::::::::::::::::::::::oKMMMMMMMMMMMMMMMMMMMMMWNXKKKXNWWMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWWNX0kxol::::::::::::::::::::::::::::::::::::::::::::::cxNMMMMMMMMMMMMMMMMMMW0dc;;,,,;;:cxNMMMMMMMMMMMMMMMMXdckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMWNK0kdocc::::::::::::::::::::::::::::::::::::::::::::::::::lOWMMMMMMMMMMMMMMMMMNx'.cxO0000kxldXMMMMMWWNNWWMMMMMK;.oNMMWWMMMMMMMMMMMMMMMMWNNWMMMMW0oxXMMMMMMWNNNWMMMMMMMMMMMWWNNWMMMMMMWNXKKXNMMMMMMWNXKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMNX0kdoc::::::::::::coddddddddl::::::::::cloddddolc:::::::::::::oKWMMMMMMMMMMMMMMMMMXc.,kNWWMMMMMWWMMMN0dc::::cd0WMMK;.oNMKol0MMMMW0loKMMN0dc:::clokNWOcoKMMWKxl::;:coONMMNklx0xl:::ckNMMNOl:::c::o0WMNkc:::::::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMWNOdlc::::::::::::::::oKWWWWWWWWOc::::::ldOKXNWWWWWNK0koc::::::::cxXMMMMMMMMMMMMMMMMMMW0c,';:codxOKNWMMXl.,lkOOxl''oNMK;.oWWk'.kMMMMWx.'OWXl',lkOOxoldXWd.,OMNx''cxOOko,.c0MXc..;lxOkl..oNNd',xKNNKd',kWO,.l0XXXKOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MWXxc:::::::::::::::::::codxxxkXMWOc::::lxKWWWX0OkkO0KNWWN0dc::::::lOWMMMMMMMMMMMMMMMMMMMMWXOxdlc;,'';dXNd.,OWMMMMWx'.kWK;.oNWk'.kWMMMWx.,ONd.,OWMMMMMMWMWd.,OMO'.oNMMMMW0;.lXXc.'xNMMMXc.:K0,.,lllllc'.lNXl,,:clodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc:::o0WWNOdlc::::ccoxKWWXxc::::coKWMMMMMMMMMMMMMMMMMMWNWMMMMWWWX0l..dNd.,OWMMMMWx'.xWK;.oNWk'.xWMMMKc.,ONd.,OWMMMMMMMMWd.,OMO'.dNMMMMM0;.lXXc.:KMMMMXl.:KK;.,oxxxxxxk0WWNKOkxdo:',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc::l0WWXxc:::::::::::oOXN0oc:cccdXMMMMMMMMMMMMMMMMMMMXdcoxO0000Ox:.;OWKc.,dO00ko,.lXMK;.oNMK:.;x00xc,.'OWKc.,dO00Okxx0Nd.,OMNd''lk00Od;.:0WXc.:XMMMMXl.:KWk;'cxO00Oxd0WKddk0000d'.xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MW0o::::::::::::::::::::::::::l0MWOc:cxNMNxc:::c::::::::clooolcccclkNMMMMMMMMMMMMMMMMMMMWOl:;;,,,,;;cdKWMMNkl:;;;;:oONMMXockWMWKo:;;:lkxclKMMNkl:;;;:ccdKWOcoKMMW0dc;;;;:lkXWMNd:dNMMMMNx:oXMWXxl::::clxXMXxlc:::::lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMN0dc::::::::::::::::::::::::l0MWOc:cOWMKo::::ccoooooooooooolcccco0WMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXNWMMMMMMMMWNXXNWMMMMMMMWMMMMMMWNXNWMMWWMMMMMMWNXXNWWMMMMWWMMMMMMWNXXNNWMMMMMWWWMMMMMMWWWMMMMMMWNNNWMMMMMMMWNNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMWN0xlc:::::::::::::::::::::lKMWOc:ckWMXo:ccccdKNNNNNNNNNNXxccccdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMNKkocc:::::::::::::c:::cdXMWkcccdXMNklccccoO000000KNMMXxccclkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMWX0xlcc:c:::cccccccccdKWWKoccclkNMNOoccccccccccoONMNklcccoOWMMMMMMMMMMMMMMMMMMMMMMMMWNKOxdddxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMNKkdlc:ccccoddxxk0NWWKdccccclkXWWXOxolllloxOXWWKxlccccdKWMMMMMMMMMMMMMMMMMMMMMMW0o;'';;::;;,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:kWWMMMMMWO;;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWN0xocccl0NWWWWNX0xlccccccccokKNWWNXXXXNWWNKkoccccclxXMMMMMMMMMMMMMMMMMMMMMMXo..:x0XWWWNX0KWMWXXNNKOOKNMMWN0kxxxOXWMMMMWNK000KNWMMWX0d'.:kOOOO0NWKdxKMNKXWMMMMMMWNKXWMMWXK000XNMMMMMWKOxxxxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMWXOdlldkkkxdolcccccccccccccldkO0KKKK0OxdlccccccclOWMMMMMMMMMMMMMMMMMMMMMWd..oXMMMMMMMMMMMM0:':c::;:kWXd;;cloc;;oXMW0l:::::;;oKMWkc;..':::::oKWk,,OW0:,oNMMMMW0:,dNNkc:::::;:xNMMXo,;clllc:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMWN0xoccccccccccccccccccccccccllllllcccccccccccoKWMMMMMMMMMMMMMMMMMMMMMNc.,OMMMMMMMMMMMMMO,.,xKNNKXXo.,kXXNXk;.oNNOxOKKXKk;.lXMWWO,.oXNWWWWMWx..kMWO,.oNMMW0:.lXMXkx0KKK0d'.xWMO,.lOKXXNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccccccccccclxXMMMMMMMMMMMMMMMMMMMMMMNo..xWMMMMMMMMMMMMO'.dWMMMMMK:.'cccccc;'lXWKxollllc,.;0MMM0,.oNWMMMMMWx..kMMWO,.oNW0;.lXMMN0xollll:'.lNMNkc::::::lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWN0kolcccccccccccccccccccccccccccccccccclONMMMMMMMMMMMMMMMMMMMMMMM0:.'dKWMMMMMMWNWMO,.dWMMMMMNo.,xKXXXXK0XNk,'oOKXKx,.,0MMM0;.lXNMMMWWWx..kMMMWO,.ok;.lXMMNo';d0KX0o..lNMWNNNXK0Oo'.dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccllclo0WMMMMMMMMMMMMMMMMMMMMMMMMXd;.':lddddl:l0MO'.dWMMMMMMXo,,coddollONk,.cddoc:,.,0MMMNo'';cddolOWx..kMMMMWO,...lXMMMNo.,lddlc:'.lNW0lclodddc';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkolcccccccccccccclllllllllllllllxXMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlc:::cloONMXkxKMMMMMMMMWXOdooodk0NMWKxooodkKKkkNMMMMN0xoollokXMXkkXMMMMMWKxdkXMMMMMNOdooodOK0x0WMN0xdollodkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdolccccccllllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdllllllllllllllllllllllllo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllllllllldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllloOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllllllokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

defined('BASEPATH') OR exit('No direct script access alloweb');
use Google\Client as GoogleClient;
use Google\Service\Oauth2;


class Login extends CI_Controller{

    public function __construct(){

        parent::__construct();
        $this->load->database();
        $this->load->model('Login_model');
        $this->load->helper('url');
		$this->load->library('session');
    }

    public function google_login(){

        
		$client   = new GoogleClient();
		$client->setApplicationName('ecommerce store');
		$client->setClientId('707076342730-as3u14itiveclv1ncuet4g4pccpbuv4l.apps.googleusercontent.com');
		$client->setClientSecret('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');
		$client->setRedirectUri('http://localhost/ci3/Login/google_login');
		$client->addScope(['https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/userinfo.profile']);


		if ($code = $this->input->get('code', true)) {
			
			$token = $client->fetchAccessTokenWithAuthCode($code);
			$client->setAccessToken($token);
			$oauth = new OAuth2($client);
			$user_info = $oauth->userinfo->get();
			
			$data['name'] 	 	     = $user_info->name;
			$data['email_address'] 	 = $user_info->email;
			$data['profile_picture'] = $user_info->picture;

			$_SESSION['access_token'] = $code;
            $_SESSION['email']        = $data['email_address'];

			
				if($user['userData'] = $this->Login_model->getUser($data['email_address'])){

				 	$this->session->set_userdata('user',$user['userData']['email_address']);

					if ($user['userData']['profile_picture'] == null) {

						$this->Login_model->updateRegister($data);
						
					}
				

				}else{

					$this->Login_model->createUser($data);

				}
				
				redirect('index');

		    }else{
				

				$url = $client->createAuthUrl();
			
				 header('Location:'.filter_var($url, FILTER_SANITIZE_URL));
		}
    }

}


// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOxdllclldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxdlc:;;;;;;;;:lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc:;;;;;;;;;;:::;:ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc::;;;;;;::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;:::::::::::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;::;::::::::::::::::::::::::ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::::::::::::::::::::::::::::::::::::l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMWNX0kxocc:::::::::::::::::::::::::::::::::::::::::oKMMMMMMMMMMMMMMMMMMMMMWNXKKKXNWWMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWWNX0kxol::::::::::::::::::::::::::::::::::::::::::::::cxNMMMMMMMMMMMMMMMMMMW0dc;;,,,;;:cxNMMMMMMMMMMMMMMMMXdckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMWNK0kdocc::::::::::::::::::::::::::::::::::::::::::::::::::lOWMMMMMMMMMMMMMMMMMNx'.cxO0000kxldXMMMMMWWNNWWMMMMMK;.oNMMWWMMMMMMMMMMMMMMMMWNNWMMMMW0oxXMMMMMMWNNNWMMMMMMMMMMMWWNNWMMMMMMWNXKKXNMMMMMMWNXKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMNX0kdoc::::::::::::coddddddddl::::::::::cloddddolc:::::::::::::oKWMMMMMMMMMMMMMMMMMXc.,kNWWMMMMMWWMMMN0dc::::cd0WMMK;.oNMKol0MMMMW0loKMMN0dc:::clokNWOcoKMMWKxl::;:coONMMNklx0xl:::ckNMMNOl:::c::o0WMNkc:::::::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMWNOdlc::::::::::::::::oKWWWWWWWWOc::::::ldOKXNWWWWWNK0koc::::::::cxXMMMMMMMMMMMMMMMMMMW0c,';:codxOKNWMMXl.,lkOOxl''oNMK;.oWWk'.kMMMMWx.'OWXl',lkOOxoldXWd.,OMNx''cxOOko,.c0MXc..;lxOkl..oNNd',xKNNKd',kWO,.l0XXXKOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MWXxc:::::::::::::::::::codxxxkXMWOc::::lxKWWWX0OkkO0KNWWN0dc::::::lOWMMMMMMMMMMMMMMMMMMMMWXOxdlc;,'';dXNd.,OWMMMMWx'.kWK;.oNWk'.kWMMMWx.,ONd.,OWMMMMMMWMWd.,OMO'.oNMMMMW0;.lXXc.'xNMMMXc.:K0,.,lllllc'.lNXl,,:clodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc:::o0WWNOdlc::::ccoxKWWXxc::::coKWMMMMMMMMMMMMMMMMMMWNWMMMMWWWX0l..dNd.,OWMMMMWx'.xWK;.oNWk'.xWMMMKc.,ONd.,OWMMMMMMMMWd.,OMO'.dNMMMMM0;.lXXc.:KMMMMXl.:KK;.,oxxxxxxk0WWNKOkxdo:',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc::l0WWXxc:::::::::::oOXN0oc:cccdXMMMMMMMMMMMMMMMMMMMXdcoxO0000Ox:.;OWKc.,dO00ko,.lXMK;.oNMK:.;x00xc,.'OWKc.,dO00Okxx0Nd.,OMNd''lk00Od;.:0WXc.:XMMMMXl.:KWk;'cxO00Oxd0WKddk0000d'.xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MW0o::::::::::::::::::::::::::l0MWOc:cxNMNxc:::c::::::::clooolcccclkNMMMMMMMMMMMMMMMMMMMWOl:;;,,,,;;cdKWMMNkl:;;;;:oONMMXockWMWKo:;;:lkxclKMMNkl:;;;:ccdKWOcoKMMW0dc;;;;:lkXWMNd:dNMMMMNx:oXMWXxl::::clxXMXxlc:::::lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMN0dc::::::::::::::::::::::::l0MWOc:cOWMKo::::ccoooooooooooolcccco0WMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXNWMMMMMMMMWNXXNWMMMMMMMWMMMMMMWNXNWMMWWMMMMMMWNXXNWWMMMMWWMMMMMMWNXXNNWMMMMMWWWMMMMMMWWWMMMMMMWNNNWMMMMMMMWNNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMWN0xlc:::::::::::::::::::::lKMWOc:ckWMXo:ccccdKNNNNNNNNNNXxccccdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMNKkocc:::::::::::::c:::cdXMWkcccdXMNklccccoO000000KNMMXxccclkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMWX0xlcc:c:::cccccccccdKWWKoccclkNMNOoccccccccccoONMNklcccoOWMMMMMMMMMMMMMMMMMMMMMMMMWNKOxdddxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMNKkdlc:ccccoddxxk0NWWKdccccclkXWWXOxolllloxOXWWKxlccccdKWMMMMMMMMMMMMMMMMMMMMMMW0o;'';;::;;,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:kWWMMMMMWO;;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWN0xocccl0NWWWWNX0xlccccccccokKNWWNXXXXNWWNKkoccccclxXMMMMMMMMMMMMMMMMMMMMMMXo..:x0XWWWNX0KWMWXXNNKOOKNMMWN0kxxxOXWMMMMWNK000KNWMMWX0d'.:kOOOO0NWKdxKMNKXWMMMMMMWNKXWMMWXK000XNMMMMMWKOxxxxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMWXOdlldkkkxdolcccccccccccccldkO0KKKK0OxdlccccccclOWMMMMMMMMMMMMMMMMMMMMMWd..oXMMMMMMMMMMMM0:':c::;:kWXd;;cloc;;oXMW0l:::::;;oKMWkc;..':::::oKWk,,OW0:,oNMMMMW0:,dNNkc:::::;:xNMMXo,;clllc:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMWN0xoccccccccccccccccccccccccllllllcccccccccccoKWMMMMMMMMMMMMMMMMMMMMMNc.,OMMMMMMMMMMMMMO,.,xKNNKXXo.,kXXNXk;.oNNOxOKKXKk;.lXMWWO,.oXNWWWWMWx..kMWO,.oNMMW0:.lXMXkx0KKK0d'.xWMO,.lOKXXNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccccccccccclxXMMMMMMMMMMMMMMMMMMMMMMNo..xWMMMMMMMMMMMMO'.dWMMMMMK:.'cccccc;'lXWKxollllc,.;0MMM0,.oNWMMMMMWx..kMMWO,.oNW0;.lXMMN0xollll:'.lNMNkc::::::lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWN0kolcccccccccccccccccccccccccccccccccclONMMMMMMMMMMMMMMMMMMMMMMM0:.'dKWMMMMMMWNWMO,.dWMMMMMNo.,xKXXXXK0XNk,'oOKXKx,.,0MMM0;.lXNMMMWWWx..kMMMWO,.ok;.lXMMNo';d0KX0o..lNMWNNNXK0Oo'.dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccllclo0WMMMMMMMMMMMMMMMMMMMMMMMMXd;.':lddddl:l0MO'.dWMMMMMMXo,,coddollONk,.cddoc:,.,0MMMNo'';cddolOWx..kMMMMWO,...lXMMMNo.,lddlc:'.lNW0lclodddc';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkolcccccccccccccclllllllllllllllxXMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlc:::cloONMXkxKMMMMMMMMWXOdooodk0NMWKxooodkKKkkNMMMMN0xoollokXMXkkXMMMMMWKxdkXMMMMMNOdooodOK0x0WMN0xdollodkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdolccccccllllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdllllllllllllllllllllllllo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllllllllldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllloOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllllllokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM