<?php
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOxdllclldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxdlc:;;;;;;;;:lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc:;;;;;;;;;;:::;:ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc::;;;;;;::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;:::::::::::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;::;::::::::::::::::::::::::ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::::::::::::::::::::::::::::::::::::l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMWNX0kxocc:::::::::::::::::::::::::::::::::::::::::oKMMMMMMMMMMMMMMMMMMMMMWNXKKKXNWWMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWWNX0kxol::::::::::::::::::::::::::::::::::::::::::::::cxNMMMMMMMMMMMMMMMMMMW0dc;;,,,;;:cxNMMMMMMMMMMMMMMMMXdckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMWNK0kdocc::::::::::::::::::::::::::::::::::::::::::::::::::lOWMMMMMMMMMMMMMMMMMNx'.cxO0000kxldXMMMMMWWNNWWMMMMMK;.oNMMWWMMMMMMMMMMMMMMMMWNNWMMMMW0oxXMMMMMMWNNNWMMMMMMMMMMMWWNNWMMMMMMWNXKKXNMMMMMMWNXKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMNX0kdoc::::::::::::coddddddddl::::::::::cloddddolc:::::::::::::oKWMMMMMMMMMMMMMMMMMXc.,kNWWMMMMMWWMMMN0dc::::cd0WMMK;.oNMKol0MMMMW0loKMMN0dc:::clokNWOcoKMMWKxl::;:coONMMNklx0xl:::ckNMMNOl:::c::o0WMNkc:::::::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMWNOdlc::::::::::::::::oKWWWWWWWWOc::::::ldOKXNWWWWWNK0koc::::::::cxXMMMMMMMMMMMMMMMMMMW0c,';:codxOKNWMMXl.,lkOOxl''oNMK;.oWWk'.kMMMMWx.'OWXl',lkOOxoldXWd.,OMNx''cxOOko,.c0MXc..;lxOkl..oNNd',xKNNKd',kWO,.l0XXXKOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MWXxc:::::::::::::::::::codxxxkXMWOc::::lxKWWWX0OkkO0KNWWN0dc::::::lOWMMMMMMMMMMMMMMMMMMMMWXOxdlc;,'';dXNd.,OWMMMMWx'.kWK;.oNWk'.kWMMMWx.,ONd.,OWMMMMMMWMWd.,OMO'.oNMMMMW0;.lXXc.'xNMMMXc.:K0,.,lllllc'.lNXl,,:clodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc:::o0WWNOdlc::::ccoxKWWXxc::::coKWMMMMMMMMMMMMMMMMMMWNWMMMMWWWX0l..dNd.,OWMMMMWx'.xWK;.oNWk'.xWMMMKc.,ONd.,OWMMMMMMMMWd.,OMO'.dNMMMMM0;.lXXc.:KMMMMXl.:KK;.,oxxxxxxk0WWNKOkxdo:',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc::l0WWXxc:::::::::::oOXN0oc:cccdXMMMMMMMMMMMMMMMMMMMXdcoxO0000Ox:.;OWKc.,dO00ko,.lXMK;.oNMK:.;x00xc,.'OWKc.,dO00Okxx0Nd.,OMNd''lk00Od;.:0WXc.:XMMMMXl.:KWk;'cxO00Oxd0WKddk0000d'.xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MW0o::::::::::::::::::::::::::l0MWOc:cxNMNxc:::c::::::::clooolcccclkNMMMMMMMMMMMMMMMMMMMWOl:;;,,,,;;cdKWMMNkl:;;;;:oONMMXockWMWKo:;;:lkxclKMMNkl:;;;:ccdKWOcoKMMW0dc;;;;:lkXWMNd:dNMMMMNx:oXMWXxl::::clxXMXxlc:::::lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMN0dc::::::::::::::::::::::::l0MWOc:cOWMKo::::ccoooooooooooolcccco0WMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXNWMMMMMMMMWNXXNWMMMMMMMWMMMMMMWNXNWMMWWMMMMMMWNXXNWWMMMMWWMMMMMMWNXXNNWMMMMMWWWMMMMMMWWWMMMMMMWNNNWMMMMMMMWNNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMWN0xlc:::::::::::::::::::::lKMWOc:ckWMXo:ccccdKNNNNNNNNNNXxccccdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMNKkocc:::::::::::::c:::cdXMWkcccdXMNklccccoO000000KNMMXxccclkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMWX0xlcc:c:::cccccccccdKWWKoccclkNMNOoccccccccccoONMNklcccoOWMMMMMMMMMMMMMMMMMMMMMMMMWNKOxdddxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMNKkdlc:ccccoddxxk0NWWKdccccclkXWWXOxolllloxOXWWKxlccccdKWMMMMMMMMMMMMMMMMMMMMMMW0o;'';;::;;,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:kWWMMMMMWO;;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWN0xocccl0NWWWWNX0xlccccccccokKNWWNXXXXNWWNKkoccccclxXMMMMMMMMMMMMMMMMMMMMMMXo..:x0XWWWNX0KWMWXXNNKOOKNMMWN0kxxxOXWMMMMWNK000KNWMMWX0d'.:kOOOO0NWKdxKMNKXWMMMMMMWNKXWMMWXK000XNMMMMMWKOxxxxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMWXOdlldkkkxdolcccccccccccccldkO0KKKK0OxdlccccccclOWMMMMMMMMMMMMMMMMMMMMMWd..oXMMMMMMMMMMMM0:':c::;:kWXd;;cloc;;oXMW0l:::::;;oKMWkc;..':::::oKWk,,OW0:,oNMMMMW0:,dNNkc:::::;:xNMMXo,;clllc:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMWN0xoccccccccccccccccccccccccllllllcccccccccccoKWMMMMMMMMMMMMMMMMMMMMMNc.,OMMMMMMMMMMMMMO,.,xKNNKXXo.,kXXNXk;.oNNOxOKKXKk;.lXMWWO,.oXNWWWWMWx..kMWO,.oNMMW0:.lXMXkx0KKK0d'.xWMO,.lOKXXNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccccccccccclxXMMMMMMMMMMMMMMMMMMMMMMNo..xWMMMMMMMMMMMMO'.dWMMMMMK:.'cccccc;'lXWKxollllc,.;0MMM0,.oNWMMMMMWx..kMMWO,.oNW0;.lXMMN0xollll:'.lNMNkc::::::lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWN0kolcccccccccccccccccccccccccccccccccclONMMMMMMMMMMMMMMMMMMMMMMM0:.'dKWMMMMMMWNWMO,.dWMMMMMNo.,xKXXXXK0XNk,'oOKXKx,.,0MMM0;.lXNMMMWWWx..kMMMWO,.ok;.lXMMNo';d0KX0o..lNMWNNNXK0Oo'.dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccllclo0WMMMMMMMMMMMMMMMMMMMMMMMMXd;.':lddddl:l0MO'.dWMMMMMMXo,,coddollONk,.cddoc:,.,0MMMNo'';cddolOWx..kMMMMWO,...lXMMMNo.,lddlc:'.lNW0lclodddc';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkolcccccccccccccclllllllllllllllxXMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlc:::cloONMXkxKMMMMMMMMWXOdooodk0NMWKxooodkKKkkNMMMMN0xoollokXMXkkXMMMMMWKxdkXMMMMMNOdooodOK0x0WMN0xdollodkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdolccccccllllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdllllllllllllllllllllllllo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllllllllldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllloOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllllllokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
defined('BASEPATH') OR exit('No direct script access allowed');

class Pages extends CI_Controller{

    public function __construct(){

        parent::__construct();
        $this->load->helper('url');
        $this->load->model('Head_model'); 
        $this->load->model('Header_model');     
        $this->load->model('Main_model');     
        $this->load->model('Product_model');   
        $this->load->model('Login_model');  
        $this->load->library('email');
        $this->load->library('hash');
        
    }


    public function index(){

        $page = "index";
      
          if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}


    //cargamos los valores de la bd
    $data['currency_language'] =   $this->Head_model->Head_views_currency();
    $data['language']          =   $this->Head_model->Head_views_language();
    $data['phone']             =   $this->Head_model->Head_views_phoneNumber();  
    $data['categorie']         =   $this->Header_model->Header_views_categorie();     
    $data['intro_slide']       =   $this->Main_model->Main_views_middle_intro_section();  
    $data['intro_banner']      =   $this->Main_model->Main_views_middle_intro_banner();     
    $data['brand']             =   $this->Main_model->Main_views_middle_intro_brand();     
    $data['nav_item']          =   $this->Main_model->Main_views_heading_center();   
    $data['tab_content_product']            =   $this->Main_model->Main_index_main_tab_content();  
    $data['shop_by_categories']             =   $this->Main_model->Main_categories();  
    $data['nav_item_middle']                =   $this->Main_model->Main_views_heading_center_middle();  
    $data['tab_content_product_middle']     =   $this->Main_model->Main_index_main_tab_content_middle();  
    $data['tab_content_product_middle_down']     =   $this->Main_model->  Main_index_main_tab_content_middle_down();  
    $data['icon_box']                            =   $this->Main_model->  Main_index_icon_box();  
    $data['article']                            =   $this->Main_model->  Main_index_blog_posts();  

    

    $this->load->view('Pages/'.$page,  $data);

}

public function home(){

    $page = "index";
  
      if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}


//cargamos los valores de la bd
$data['currency_language'] =   $this->Head_model->Head_views_currency();
$data['language']          =   $this->Head_model->Head_views_language();
$data['phone']             =   $this->Head_model->Head_views_phoneNumber();  
$data['categorie']         =   $this->Header_model->Header_views_categorie();  
$data['intro_slide']       =   $this->Main_model->Main_views_middle_intro_section();    
$data['intro_banner']      =   $this->Main_model->Main_views_middle_intro_banner();   
$data['brand']             =   $this->Main_model->Main_views_middle_intro_brand();    
$data['nav_item']          =   $this->Main_model->Main_views_heading_center();    
$data['tab_content_product']            =   $this->Main_model->Main_index_main_tab_content();  
$data['shop_by_categories']             =   $this->Main_model->Main_categories();       
$data['nav_item_middle']                =   $this->Main_model->Main_views_heading_center_middle();  
$data['tab_content_product_middle']     =   $this->Main_model->Main_index_main_tab_content_middle();  
$data['tab_content_product_middle_down']     =   $this->Main_model->  Main_index_main_tab_content_middle_down();  
$data['icon_box']                            =   $this->Main_model->  Main_index_icon_box();  
$data['article']                            =   $this->Main_model->  Main_index_blog_posts(); 
 
$this->load->view('Pages/'.$page,  $data);

}


public function product(){

    $page = "product";
    
    if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}

     //cargamos los valores de la bd
     $data['categorie']         =   $this->Header_model->Header_views_categorie();  
     $data['currency_language'] =   $this->Head_model->Head_views_currency();
     $data['language']          =   $this->Head_model->Head_views_language();
     $data['phone']             =   $this->Head_model->Head_views_phoneNumber();
    //  $data['categorie']      =   $this->Header_model->Header_views_categorie();  
    $data['product_gallerie']             =   $this->Product_model->product_details_top_product_gallery(); 
    $data['product_gallerie_color']       =   $this->Product_model->product_details_top_product_gallery_color(); 
    $data['product_gallerie_size']        =   $this->Product_model->product_details_top_product_gallery_size(); 
    $data['product_gallerie_breadcrumb']  =   $this->Product_model->product_details_top_product_gallery_breadcrumb(); 
    $data['additional_information']       =   $this->Product_model->product_details_top_product_gallery_additional_information(); 

    if ( isset($_GET['categorie'], $_GET['product'])) {

        $categorie_id = $_GET['categorie'];
        $product_id   = $_GET['product'];

        // $send_data = $this->Product_model->product_details_top_product_gallery();
        // $categorie_id = base64_encode($_GET['categorie']);
        // $product_id   = urlencode($_GET['categorie']);

        // $categorie_id = urlencode($_GET['categorie']);
        // $product_id   = urlencode($_GET['product']);
        //  echo  $categorie_id.'espacio'.$product_id ;

        // echo $_GET['product'];
          
        }else {
            redirect(base_url());
        }
       
    
    $this->load->view('Pages/'.$page, $data);



}

public function productByColor(){


    $page = "product";
    
    if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}

     //cargamos los valores de la bd
     $data['categorie']         =   $this->Header_model->Header_views_categorie();  
     $data['currency_language'] =   $this->Head_model->Head_views_currency();
     $data['language']          =   $this->Head_model->Head_views_language();
     $data['phone']             =   $this->Head_model->Head_views_phoneNumber();
    //  $data['categorie']      =   $this->Header_model->Header_views_categorie();  
    $data['product_gallerie']        =   $this->Product_model->product_details_top_product_gallery(); 
    $data['product_gallerie_color']  =   $this->Product_model->product_details_top_product_gallery_color(); 
    $data['product_gallerie_size']  =   $this->Product_model->product_details_top_product_gallery_size(); 
    $data['product_gallerie_breadcrumb']  =   $this->Product_model->product_details_top_product_gallery_breadcrumb(); 
    $data['additional_information']       =   $this->Product_model->product_details_top_product_gallery_additional_information(); 
    
    if ( isset($_GET['color'], $_GET['product'])) {

        $product_id   = $_GET['product'];

        // var_dump($data['product_gallerie'] );
          
        }else {
            redirect(base_url());
        }
       
    
    $this->load->view('Pages/'.$page, $data);


}


public function blog(){

    $page = "blog";
    
    if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}

    //  //cargamos los valores de la bd
     $data['currency_language'] =   $this->Head_model->Head_views_currency();
     $data['language']          =   $this->Head_model->Head_views_language();
     $data['phone']             =   $this->Head_model->Head_views_phoneNumber();
     $data['categorie']         =   $this->Header_model->Header_views_categorie();        

    $this->load->view('Pages/'.$page,$data);
}


public function about(){

    $page = "about";
    
    if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}

    //  //cargamos los valores de la bd
     $data['currency_language'] =   $this->Head_model->Head_views_currency();
     $data['language']          =   $this->Head_model->Head_views_language();
     $data['phone']             =   $this->Head_model->Head_views_phoneNumber();
     $data['categorie']         =   $this->Header_model->Header_views_categorie();        

    $this->load->view('Pages/'.$page, $data);
}



public function cart(){

    $page = "cart";
    
    if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}

     //cargamos los valores de la bd
      $data['categorie']         =   $this->Header_model->Header_views_categorie();  
      $data['currency_language'] =   $this->Head_model->Head_views_currency();
      $data['language']          =   $this->Head_model->Head_views_language();
      $data['phone']             =   $this->Head_model->Head_views_phoneNumber();
    //  $data['product_gallerie']  =   $this->Product_model->product_details_top_product_gallery();       
 

    $this->load->view('Pages/'.$page, $data);
}


public function checkout(){

    $page = "checkout";
    
    if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}

     //cargamos los valores de la bd
      $data['categorie']         =   $this->Header_model->Header_views_categorie();  
      $data['currency_language'] =   $this->Head_model->Head_views_currency();
      $data['language']          =   $this->Head_model->Head_views_language();
      $data['phone']             =   $this->Head_model->Head_views_phoneNumber();
    //  $data['product_gallerie']  =   $this->Product_model->product_details_top_product_gallery();       
 

    $this->load->view('Pages/'.$page, $data);
}




public function dashboard(){

    $page = "dashboard";
    
    if (!file_exists(APPPATH.'views/pages/'.$page.'.php')) { show_404();}

     //cargamos los valores de la bd
      $data['categorie']         =   $this->Header_model->Header_views_categorie();  
      $data['currency_language'] =   $this->Head_model->Head_views_currency();
      $data['language']          =   $this->Head_model->Head_views_language();
      $data['phone']             =   $this->Head_model->Head_views_phoneNumber();
    //  $data['product_gallerie']  =   $this->Product_model->product_details_top_product_gallery();       
 

    $this->load->view('Pages/'.$page, $data);
}



public function formPostRegister(){


            $recaptchaResponse = trim($this->input->post('g-recaptcha-response'));

            $userIp = $this->input->ip_address();
            $secret = $this->config->item('google_secret');
            $url="https://www.google.com/recaptcha/api/siteverify?secret=".$secret."&response=".$recaptchaResponse."&remoteip=".$userIp;

            $ch = curl_init(); 

            curl_setopt($ch, CURLOPT_URL, $url); 

            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 

            $output = curl_exec($ch); 

            curl_close($ch);      

        
            $status= json_decode($output, true);

            if ($status['success']) {

                // creamos el usuario innactivo en la bd
                if ( isset($_POST['register-email']) && 
                           $_POST['register-email'] !="" &&
                     isset($_POST['register-password']) && 
                           $_POST['register-password'] !="") {

                            $_POST['register-email'] = strtolower($_POST['register-email']);

                        if (preg_match('/^[^0-9][a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[@][a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{2,4}$/', $_POST['register-email'])) {
                            
                                $data['email_address'] = $_POST['register-email'];
                                

                                $user =  $this->Login_model->getUser($data['email_address']);

                                if ( $user !="") {


                                        redirect('index', 'refresh');

                                }else{

                                        $data['email_address'] = $_POST['register-email'];
                                        $data['login_auth_id'] = $this->hash->encrypt($_POST['register-password']);
                                        $data['code']          = md5($_POST['register-email']);

                                        $this->Login_model->createUser($data);

                                        $this->session->sess_destroy();

                                            // envio de correo de validacion
                                            $this->email->to('contacto@jadergolindano.com.ve');
                                            $this->email->from("golindano.jader@gmail.com","sdasdasdasd");
                                            $this->email->subject('Test Email (TEXT)');
                                            $this->email->message('Text email testing by CodeIgniter Email library.');
                                            $this->email->send();

                                            redirect('index', 'refresh');
                                      }
                                    
                                }

                        


                            // print_r('Google Recaptcha Successful');

                      

                            exit;

                        }else{

                            $this->session->set_flashdata('flashError', 'Sorry Google Recaptcha Unsuccessful!');
                            redirect('index', 'refresh');

                        }


                  }
        }
   



}

// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOxdllclldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxdlc:;;;;;;;;:lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc:;;;;;;;;;;:::;:ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxolc::;;;;;;::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;:::::::::::::::::::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::;;::;::::::::::::::::::::::::ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc::::::::::::::::::::::::::::::::::::l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMWNX0kxocc:::::::::::::::::::::::::::::::::::::::::oKMMMMMMMMMMMMMMMMMMMMMWNXKKKXNWWMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWWNX0kxol::::::::::::::::::::::::::::::::::::::::::::::cxNMMMMMMMMMMMMMMMMMMW0dc;;,,,;;:cxNMMMMMMMMMMMMMMMMXdckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMWNK0kdocc::::::::::::::::::::::::::::::::::::::::::::::::::lOWMMMMMMMMMMMMMMMMMNx'.cxO0000kxldXMMMMMWWNNWWMMMMMK;.oNMMWWMMMMMMMMMMMMMMMMWNNWMMMMW0oxXMMMMMMWNNNWMMMMMMMMMMMWWNNWMMMMMMWNXKKXNMMMMMMWNXKKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMNX0kdoc::::::::::::coddddddddl::::::::::cloddddolc:::::::::::::oKWMMMMMMMMMMMMMMMMMXc.,kNWWMMMMMWWMMMN0dc::::cd0WMMK;.oNMKol0MMMMW0loKMMN0dc:::clokNWOcoKMMWKxl::;:coONMMNklx0xl:::ckNMMNOl:::c::o0WMNkc:::::::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMWNOdlc::::::::::::::::oKWWWWWWWWOc::::::ldOKXNWWWWWNK0koc::::::::cxXMMMMMMMMMMMMMMMMMMW0c,';:codxOKNWMMXl.,lkOOxl''oNMK;.oWWk'.kMMMMWx.'OWXl',lkOOxoldXWd.,OMNx''cxOOko,.c0MXc..;lxOkl..oNNd',xKNNKd',kWO,.l0XXXKOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MWXxc:::::::::::::::::::codxxxkXMWOc::::lxKWWWX0OkkO0KNWWN0dc::::::lOWMMMMMMMMMMMMMMMMMMMMWXOxdlc;,'';dXNd.,OWMMMMWx'.kWK;.oNWk'.kWMMMWx.,ONd.,OWMMMMMMWMWd.,OMO'.oNMMMMW0;.lXXc.'xNMMMXc.:K0,.,lllllc'.lNXl,,:clodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc:::o0WWNOdlc::::ccoxKWWXxc::::coKWMMMMMMMMMMMMMMMMMMWNWMMMMWWWX0l..dNd.,OWMMMMWx'.xWK;.oNWk'.xWMMMKc.,ONd.,OWMMMMMMMMWd.,OMO'.dNMMMMM0;.lXXc.:KMMMMXl.:KK;.,oxxxxxxk0WWNKOkxdo:',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MNkc::::::::::::::::::::::::::l0MWOc::l0WWXxc:::::::::::oOXN0oc:cccdXMMMMMMMMMMMMMMMMMMMXdcoxO0000Ox:.;OWKc.,dO00ko,.lXMK;.oNMK:.;x00xc,.'OWKc.,dO00Okxx0Nd.,OMNd''lk00Od;.:0WXc.:XMMMMXl.:KWk;'cxO00Oxd0WKddk0000d'.xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MW0o::::::::::::::::::::::::::l0MWOc:cxNMNxc:::c::::::::clooolcccclkNMMMMMMMMMMMMMMMMMMMWOl:;;,,,,;;cdKWMMNkl:;;;;:oONMMXockWMWKo:;;:lkxclKMMNkl:;;;:ccdKWOcoKMMW0dc;;;;:lkXWMNd:dNMMMMNx:oXMWXxl::::clxXMXxlc:::::lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMN0dc::::::::::::::::::::::::l0MWOc:cOWMKo::::ccoooooooooooolcccco0WMMMMMMMMMMMMMMMMMMMMMMWNXKKKKXNWMMMMMMMMWNXXNWMMMMMMMWMMMMMMWNXNWMMWWMMMMMMWNXXNWWMMMMWWMMMMMMWNXXNNWMMMMMWWWMMMMMMWWWMMMMMMWNNNWMMMMMMMWNNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMWN0xlc:::::::::::::::::::::lKMWOc:ckWMXo:ccccdKNNNNNNNNNNXxccccdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMNKkocc:::::::::::::c:::cdXMWkcccdXMNklccccoO000000KNMMXxccclkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMWX0xlcc:c:::cccccccccdKWWKoccclkNMNOoccccccccccoONMNklcccoOWMMMMMMMMMMMMMMMMMMMMMMMMWNKOxdddxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMNKkdlc:ccccoddxxk0NWWKdccccclkXWWXOxolllloxOXWWKxlccccdKWMMMMMMMMMMMMMMMMMMMMMMW0o;'';;::;;,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:kWWMMMMMWO;;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMWN0xocccl0NWWWWNX0xlccccccccokKNWWNXXXXNWWNKkoccccclxXMMMMMMMMMMMMMMMMMMMMMMXo..:x0XWWWNX0KWMWXXNNKOOKNMMWN0kxxxOXWMMMMWNK000KNWMMWX0d'.:kOOOO0NWKdxKMNKXWMMMMMMWNKXWMMWXK000XNMMMMMWKOxxxxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMWXOdlldkkkxdolcccccccccccccldkO0KKKK0OxdlccccccclOWMMMMMMMMMMMMMMMMMMMMMWd..oXMMMMMMMMMMMM0:':c::;:kWXd;;cloc;;oXMW0l:::::;;oKMWkc;..':::::oKWk,,OW0:,oNMMMMW0:,dNNkc:::::;:xNMMXo,;clllc:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMWN0xoccccccccccccccccccccccccllllllcccccccccccoKWMMMMMMMMMMMMMMMMMMMMMNc.,OMMMMMMMMMMMMMO,.,xKNNKXXo.,kXXNXk;.oNNOxOKKXKk;.lXMWWO,.oXNWWWWMWx..kMWO,.oNMMW0:.lXMXkx0KKK0d'.xWMO,.lOKXXNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccccccccccclxXMMMMMMMMMMMMMMMMMMMMMMNo..xWMMMMMMMMMMMMO'.dWMMMMMK:.'cccccc;'lXWKxollllc,.;0MMM0,.oNWMMMMMWx..kMMWO,.oNW0;.lXMMN0xollll:'.lNMNkc::::::lkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMWN0kolcccccccccccccccccccccccccccccccccclONMMMMMMMMMMMMMMMMMMMMMMM0:.'dKWMMMMMMWNWMO,.dWMMMMMNo.,xKXXXXK0XNk,'oOKXKx,.,0MMM0;.lXNMMMWWWx..kMMMWO,.ok;.lXMMNo';d0KX0o..lNMWNNNXK0Oo'.dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlccccccccccccccccccccccccccccllclo0WMMMMMMMMMMMMMMMMMMMMMMMMXd;.':lddddl:l0MO'.dWMMMMMMXo,,coddollONk,.cddoc:,.,0MMMNo'';cddolOWx..kMMMMWO,...lXMMMNo.,lddlc:'.lNW0lclodddc';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkolcccccccccccccclllllllllllllllxXMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlc:::cloONMXkxKMMMMMMMMWXOdooodk0NMWKxooodkKKkkNMMMMN0xoollokXMXkkXMMMMMWKxdkXMMMMMNOdooodOK0x0WMN0xdollodkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdolccccccllllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdllllllllllllllllllllllllo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllllllllldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllllllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxollllllllllllllloOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdlllllllllllllxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllllllokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xollllox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM